Populate post from yaml
Cannold/ghost pull request #5
Opened 2019-07-09 23:33 UTC by thvu11

`./ghost.sh import` will handle following content:
- html content of posts
- link to PDF files
- link to images

2019-07-11 02:05 UTC, adamc00 requested changes

2019-07-11 02:05 UTC, adamc00 commented on data/backup.yml
> -    publish_on: April 01, 2011
Altering the input file to match your input requirements should be avoided. It's better to either process the data on the fly into the format you want or write out a new file for input into the next stage. While the file is in version control so you can always go back and see what you have done it is better to keep the supplied source around so you can always easily see what the original content looked like.

2019-07-11 02:30 UTC, thvu11 commented
I revert that commit and add a format time check for that case

2019-08-21 06:21 UTC, thvu11 commented
You have issue running the export?

2019-08-21 06:46 UTC, adamc00 commented
> You have issue running the export?

Just accidental commit of logs from ghost. I've added a .gitignore for them.

2019-08-22 01:03 UTC, thvu11 commented
Tags, publication history and content link has been added.

2019-08-30 06:20 UTC, adamc00 approved these changes

2019-08-30 06:21 UTC, merged